import React, { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { Logo } from "../components/Logo";
import { ArrowRight, FileText, MessageSquare, Download, Layers, Sparkles, Check, Crown, ChevronDown, Code2 } from "lucide-react";
import { captureEvent } from "../lib/analytics";
import { useDocumentTitle } from "../hooks/useDocumentTitle";
import { Footer } from "../components/Footer";

const FAQ_ITEMS = [
  {
    q: "How does Megabyte PDF work?",
    a: "Type a prompt — \"create a two-page invoice for $4,500 of consulting work\" — and the AI writes the HTML and CSS for a print-ready 8.5 × 11 document. You see every page render in real time. Hit Download to get a real PDF.",
  },
  {
    q: "Do I need an account to try it?",
    a: "No. Guest mode gives you 10 AI prompts per day with live preview in your browser. Sign up (free) to save projects and build on them across sessions.",
  },
  {
    q: "Can I download a real PDF?",
    a: "Yes — Pro users ($9/mo) get true PDF exports generated by Cloudflare Browser Rendering. The file has selectable text, embedded fonts, and correct page dimensions. Guest and Free tiers see the live preview only.",
  },
  {
    q: "What kinds of documents can it make?",
    a: "Invoices, resumes, reports, contracts, proposals, cover letters, technical specs — anything that maps to a printed page. If you can describe it in plain English, Megabyte PDF can draft it.",
  },
  {
    q: "Can I share a document with a client?",
    a: "Pro users get a public share link. Recipients see a read-only preview of your document — no account required on their end.",
  },
  {
    q: "How do version snapshots work?",
    a: "Every AI response creates a snapshot. You can restore any previous version of your document with one click — handy when a prompt takes the design in the wrong direction.",
  },
];

export default function Landing() {
  useDocumentTitle("Chat your way to print-perfect PDFs");
  const heroRef = useRef<HTMLElement | null>(null);
  useEffect(() => {
    const el = heroRef.current;
    if (!el || !window.matchMedia("(pointer: fine)").matches) return;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    let raf = 0;
    function onMove(e: PointerEvent) {
      cancelAnimationFrame(raf);
      raf = requestAnimationFrame(() => {
        const rect = el!.getBoundingClientRect();
        const x = ((e.clientX - rect.left) / rect.width) * 100;
        const y = ((e.clientY - rect.top) / rect.height) * 100;
        el!.style.setProperty("--spot-x", `${x}%`);
        el!.style.setProperty("--spot-y", `${y}%`);
      });
    }
    el.addEventListener("pointermove", onMove);
    return () => {
      cancelAnimationFrame(raf);
      el.removeEventListener("pointermove", onMove);
    };
  }, []);
  return (
    <div className="min-h-screen flex flex-col">
      <a href="#main-content" className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:px-4 focus:py-2 focus:bg-[var(--color-cyan)] focus:text-[#060610] focus:rounded-md focus:font-semibold focus:text-sm">Skip to content</a>
      <header className="px-6 lg:px-10 py-5 flex items-center justify-between border-b border-[var(--color-line)]">
        <Link to="/" aria-label="Megabyte PDF home">
          <Logo size={32} />
        </Link>
        <nav aria-label="Main navigation" className="flex items-center gap-2">
          <Link to="/sign-in" className="btn btn-ghost text-sm px-3 py-2 underline-hover" aria-label="Sign in" onClick={() => captureEvent("landing_nav_signin")}>
            Sign in
          </Link>
          <Link to="/sign-in" className="btn btn-primary text-sm px-3 py-2" onClick={() => captureEvent("landing_nav_getstarted")}>
            Get started <ArrowRight size={14} className="hidden sm:block" />
          </Link>
        </nav>
      </header>

      <main id="main-content" className="flex-1">
        <section ref={heroRef} className="relative overflow-hidden">
          <div className="aurora" aria-hidden="true" />
          <div className="spotlight" aria-hidden="true" />
          <div className="max-w-6xl mx-auto px-6 lg:px-10 pt-20 lg:pt-32 pb-16 text-center animate-fade-in-up relative">
            <p className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-[var(--color-cyan)] mb-6">
              <span className="size-1.5 rounded-full bg-[var(--color-cyan)] animate-pulse" />
              Print-perfect PDFs from a chat
            </p>
            <h1
              className="text-5xl lg:text-7xl font-bold tracking-tight text-balance leading-[1.05] mb-6"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Chat your way to a{" "}
              <span
                className="bg-gradient-to-r from-[var(--color-cyan)] to-[var(--color-violet)] bg-clip-text text-transparent type-on"
                style={{ ["--type-dur" as string]: "1.1s", ["--type-steps" as string]: 13 }}
              >
                printable PDF
              </span>
              .
            </h1>
            <p className="text-lg lg:text-xl text-[var(--color-muted)] max-w-2xl mx-auto text-pretty mb-10">
              Prompt the AI. Watch every page render in real time at 8.5 × 11. Download a real
              PDF — text-selectable, print-ready, your name on it.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
              <Link to="/guest" className="btn btn-primary text-base px-6 py-3" onClick={() => captureEvent("landing_hero_try_guest")}>
                <Sparkles size={18} /> Try it now — no signup
              </Link>
              <Link to="/sign-in" className="btn btn-ghost text-base px-6 py-3 underline-hover" onClick={() => captureEvent("landing_hero_signup")}>
                Create an account <ArrowRight size={16} />
              </Link>
            </div>
            <p className="text-xs text-[var(--color-muted)] mt-6">
              10 free guest prompts a day. Sign in to save, share, and download real PDFs.
            </p>
          </div>
        </section>

        <section className="max-w-6xl mx-auto px-6 lg:px-10 pb-24">
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">
            <Feature
              icon={<MessageSquare size={20} />}
              title="Prompt, don't fuss"
              body="Tell the AI what you need. It writes print-ready HTML and CSS — you just review and adjust."
            />
            <Feature
              icon={<Layers size={20} />}
              title="Every page on screen"
              body="See each page in a vertical stack at 8.5 × 11. Scroll through like a stack of paper."
            />
            <Feature
              icon={<Download size={20} />}
              title="Real PDFs"
              body="True PDF export — text-selectable, embedded fonts, exact page dimensions. Not a screenshot."
            />
            <Feature
              icon={<Code2 size={20} />}
              title="Edit the source"
              body="Open the code panel, tweak HTML and CSS directly, see the preview update in real time."
            />
          </div>
        </section>

        {/* Document types */}
        <section className="max-w-6xl mx-auto px-6 lg:px-10 pb-24">
          <p className="text-center text-xs uppercase tracking-[0.2em] text-[var(--color-muted)] mb-6">Works for any document</p>
          <div className="flex flex-wrap gap-2 justify-center">
            {[
              "Invoice", "Resume", "Cover letter", "NDA", "Contract",
              "Business proposal", "Report", "Statement of work",
              "Meeting agenda", "Certificate", "Letterhead", "Spec sheet",
            ].map((t) => (
              <span
                key={t}
                className="px-3 py-1.5 rounded-full text-sm border border-[var(--color-line)] text-[var(--color-muted)] bg-[var(--color-bg-card)]"
              >
                {t}
              </span>
            ))}
          </div>
        </section>

        {/* Pricing */}
        <section className="max-w-6xl mx-auto px-6 lg:px-10 pb-24" id="pricing">
          <div className="text-center mb-12">
            <h2
              className="text-3xl lg:text-4xl font-bold mb-3 text-balance"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Simple pricing.
            </h2>
            <p className="text-[var(--color-muted)] max-w-md mx-auto">
              Start free. Pay when you need real PDFs.
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-4 items-start">
            <PricingTier
              name="Guest"
              price="Free"
              sub="no account needed"
              cta="Try now"
              ctaLink="/guest"
              features={[
                "10 AI prompts per day",
                "Live preview in browser",
                "Sonnet model",
              ]}
              locked={[
                "Save projects",
                "PDF download",
                "Share links",
              ]}
            />
            <PricingTier
              name="Free"
              price="$0"
              sub="sign in required"
              cta="Create account"
              ctaLink="/sign-in"
              features={[
                "1 saved project",
                "Full chat history",
                "Sonnet model",
                "Version snapshots",
              ]}
              locked={[
                "PDF download",
                "Share links",
                "Opus model",
              ]}
            />
            <PricingTier
              name="Pro"
              price="$9"
              sub="per month"
              cta="Upgrade to Pro"
              ctaLink="/sign-in"
              highlight
              features={[
                "10 projects",
                "PDF export (real files)",
                "Public share links",
                "Claude Opus 4.7",
                "Sonnet + version history",
                "Cancel anytime",
              ]}
              locked={[]}
            />
          </div>
        </section>

        {/* FAQ */}
        <section className="max-w-3xl mx-auto px-6 lg:px-10 pb-24">
          <div className="text-center mb-10">
            <h2
              className="text-3xl lg:text-4xl font-bold mb-3 text-balance"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Common questions.
            </h2>
          </div>
          <dl className="space-y-2">
            {FAQ_ITEMS.map((item) => (
              <FaqItem key={item.q} q={item.q} a={item.a} />
            ))}
          </dl>
        </section>

        <section className="max-w-6xl mx-auto px-6 lg:px-10 pb-24">
          <div className="card p-8 lg:p-12 text-center">
            <FileText size={32} className="mx-auto mb-4 text-[var(--color-cyan)]" />
            <h2
              className="text-3xl lg:text-4xl font-bold mb-3 text-balance"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Built for documents that ship.
            </h2>
            <p className="text-[var(--color-muted)] max-w-xl mx-auto mb-8 text-pretty">
              Every project has its own AI chat history. Snapshots on every turn — restore any
              version. Public share links when you want feedback before you print.
            </p>
            <Link to="/guest" className="btn btn-primary text-base px-6 py-3" onClick={() => captureEvent("landing_footer_cta")}>
              Try it free <ArrowRight size={18} />
            </Link>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}

function FaqItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  const id = `faq-${q.slice(0, 20).replace(/\W+/g, "-").toLowerCase()}`;
  return (
    <div className="card overflow-hidden">
      <dt>
        <button
          type="button"
          aria-expanded={open}
          aria-controls={id}
          onClick={() => { setOpen((v) => !v); if (!open) captureEvent("landing_faq_open", { question: q }); }}
          className="w-full flex items-center justify-between gap-4 px-5 py-4 text-left text-sm font-medium hover:bg-white/[0.03] transition-colors"
        >
          <span>{q}</span>
          <ChevronDown
            size={16}
            className="text-[var(--color-muted)] shrink-0 transition-transform duration-200 motion-reduce:transition-none"
            style={{ transform: open ? "rotate(180deg)" : "rotate(0deg)" }}
            aria-hidden="true"
          />
        </button>
      </dt>
      <dd
        id={id}
        aria-hidden={!open}
        className="grid transition-[grid-template-rows] duration-200 ease-out motion-reduce:transition-none"
        style={{ gridTemplateRows: open ? "1fr" : "0fr" }}
      >
        <div className="overflow-hidden">
          <p className="px-5 pb-4 text-sm text-[var(--color-muted)] text-pretty leading-relaxed">{a}</p>
        </div>
      </dd>
    </div>
  );
}

function Feature({
  icon,
  title,
  body,
}: {
  icon: React.ReactNode;
  title: string;
  body: string;
}) {
  return (
    <div className="card p-6">
      <div className="size-10 rounded-lg bg-[var(--color-cyan)]/10 grid place-items-center text-[var(--color-cyan)] mb-4">
        {icon}
      </div>
      <h3 className="font-semibold text-base mb-1.5">{title}</h3>
      <p className="text-sm text-[var(--color-muted)] text-pretty">{body}</p>
    </div>
  );
}

function PricingTier({
  name,
  price,
  sub,
  cta,
  ctaLink,
  features,
  locked,
  highlight = false,
}: {
  name: string;
  price: string;
  sub: string;
  cta: string;
  ctaLink: string;
  features: string[];
  locked: string[];
  highlight?: boolean;
}) {
  return (
    <div
      className={`card p-6 flex flex-col gap-5 ${
        highlight
          ? "border-[var(--color-cyan)]/40 bg-gradient-to-b from-[var(--color-cyan)]/5 to-transparent"
          : ""
      }`}
    >
      {highlight && (
        <div className="flex items-center gap-1.5 text-xs font-semibold text-[var(--color-cyan)] uppercase tracking-widest">
          <Crown size={13} /> Most popular
        </div>
      )}
      <div>
        <p className="text-sm text-[var(--color-muted)] mb-1">{name}</p>
        <div className="flex items-baseline gap-1">
          <span className="text-3xl font-bold" style={{ fontFamily: "var(--font-display)" }}>
            {price}
          </span>
          <span className="text-[var(--color-muted)] text-sm">{sub}</span>
        </div>
      </div>
      <ul className="space-y-2 flex-1">
        {features.map((f) => (
          <li key={f} className="flex items-start gap-2 text-sm">
            <Check size={14} className="text-[var(--color-cyan)] mt-0.5 shrink-0" />
            {f}
          </li>
        ))}
        {locked.map((f) => (
          <li key={f} className="flex items-start gap-2 text-sm text-[var(--color-muted)] line-through">
            <span className="size-3.5 mt-0.5 shrink-0 rounded-full border border-current inline-block" />
            {f}
          </li>
        ))}
      </ul>
      <Link
        to={ctaLink}
        className={`btn text-sm w-full justify-center ${highlight ? "btn-primary" : "btn-ghost"}`}
        style={{ minHeight: 40 }}
        onClick={() => captureEvent("landing_pricing_cta", { tier: name })}
      >
        {cta} {highlight && <ArrowRight size={14} />}
      </Link>
    </div>
  );
}
