import { Link } from "react-router-dom";
import { Logo } from "../components/Logo";
import { ArrowLeft } from "lucide-react";
import { useDocumentTitle } from "../hooks/useDocumentTitle";

export default function Terms() {
  useDocumentTitle("Terms of Service — User agreement");
  return (
    <div className="min-h-screen flex flex-col bg-[var(--color-bg)] text-[var(--color-fg)]">
      <header className="px-6 lg:px-10 py-5 flex items-center gap-4 border-b border-[var(--color-line)]">
        <a href="#main-content" className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:px-4 focus:py-2 focus:bg-[var(--color-cyan)] focus:text-[#060610] focus:rounded-md focus:font-semibold focus:text-sm">Skip to content</a>
        <Link to="/" aria-label="Back to home" className="inline-flex items-center gap-2 text-sm text-[var(--color-muted)] underline-hover">
          <ArrowLeft size={16} /> Home
        </Link>
        <Logo size={28} className="ml-auto" />
      </header>

      <main id="main-content" className="flex-1 max-w-3xl mx-auto w-full px-6 lg:px-10 py-16">
        <h1 className="text-4xl font-bold mb-2" style={{ fontFamily: "var(--font-display)" }}>
          Terms of Service
        </h1>
        <p className="text-sm text-[var(--color-muted)] mb-12">Last updated May 4, 2025</p>

        <Section title="Agreement">
          <p>By accessing or using Megabyte PDF ("Service") you agree to these Terms. If you do not agree, do not use the Service. These Terms form a binding contract between you and Megabyte Labs ("we", "us", "our").</p>
        </Section>

        <Section title="Service description">
          <p>Megabyte PDF is an AI-assisted document editor that generates HTML/CSS from natural-language prompts and renders print-quality PDFs. The Service includes a browser-based editor, saved projects, AI chat history, and PDF export.</p>
        </Section>

        <Section title="Accounts">
          <p>You must be at least 13 years old to create an account. You are responsible for maintaining the confidentiality of your login credentials. Notify us immediately if you suspect unauthorised access. We may suspend or terminate accounts that violate these Terms.</p>
        </Section>

        <Section title="Acceptable use">
          <p>You may use the Service for any lawful personal or commercial document creation. You may not:</p>
          <ul className="list-disc list-inside space-y-1 text-sm">
            <li>Use the Service to generate illegal, harmful, or deceptive content</li>
            <li>Attempt to reverse-engineer, scrape, or stress-test the Service</li>
            <li>Resell access to the Service without prior written permission</li>
            <li>Use the Service to infringe third-party intellectual property</li>
          </ul>
        </Section>

        <Section title="Your content">
          <p>You retain all rights to the documents you create. By using the Service you grant us a limited licence to process, render, and store your content solely to provide the Service. We claim no ownership of your documents.</p>
        </Section>

        <Section title="AI output">
          <p>Content generated by the AI is provided as-is. You are responsible for reviewing AI output before relying on it professionally or legally. We make no guarantees that AI-generated documents are accurate, complete, or suitable for any specific purpose.</p>
        </Section>

        <Section title="Free tier">
          <p>Guest users receive 10 AI prompts per day. Free-tier signed-in users receive 1 saved project. We reserve the right to adjust these limits with 14 days' notice posted on the Service.</p>
        </Section>

        <Section title="Billing">
          <p>Pro plans are billed monthly via Stripe. You may cancel at any time from your account settings; access continues until the end of your billing period. We do not offer refunds for partial months except where required by law. Prices may change with 30 days' notice.</p>
        </Section>

        <Section title="Availability">
          <p>We aim for high availability but do not guarantee uninterrupted service. Planned maintenance will be announced where practical. We are not liable for losses arising from downtime.</p>
        </Section>

        <Section title="Disclaimers">
          <p>The Service is provided "as is" without warranty of any kind. To the maximum extent permitted by law, we disclaim all implied warranties, including fitness for a particular purpose and non-infringement.</p>
        </Section>

        <Section title="Limitation of liability">
          <p>Our total liability to you for any claim arising from or related to the Service shall not exceed the amount you paid us in the 12 months preceding the claim. We are not liable for indirect, incidental, or consequential damages.</p>
        </Section>

        <Section title="Indemnification">
          <p>You agree to indemnify and hold Megabyte Labs harmless from claims, losses, or damages arising from your use of the Service or your violation of these Terms.</p>
        </Section>

        <Section title="Governing law">
          <p>These Terms are governed by the laws of the State of Delaware, USA. Disputes shall be resolved by binding arbitration under AAA rules, except either party may seek injunctive relief in any court of competent jurisdiction.</p>
        </Section>

        <Section title="Changes">
          <p>We may modify these Terms at any time. Material changes will be communicated by updating the date above and emailing registered users where practical. Continued use after the effective date constitutes acceptance.</p>
        </Section>

        <Section title="Contact">
          <p>Megabyte Labs · <a href="mailto:hey@megabyte.space" className="text-[var(--color-cyan)] underline-hover">hey@megabyte.space</a></p>
        </Section>
      </main>

      <footer className="border-t border-[var(--color-line)] px-6 lg:px-10 py-8 text-center text-sm text-[var(--color-muted)]">
        <div className="flex flex-col sm:flex-row items-center justify-between gap-3 max-w-6xl mx-auto">
          <span>© {new Date().getFullYear()} Megabyte Labs</span>
          <nav aria-label="Legal and contact" className="flex items-center gap-4">
            <Link to="/privacy" className="underline-hover">Privacy</Link>
            <Link to="/terms" className="underline-hover" aria-current="page">Terms</Link>
            <a href="mailto:hey@megabyte.space" className="underline-hover">hey@megabyte.space</a>
          </nav>
        </div>
      </footer>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-semibold mb-3" style={{ fontFamily: "var(--font-display)" }}>{title}</h2>
      <div className="text-[var(--color-muted)] leading-relaxed text-sm space-y-3">{children}</div>
    </section>
  );
}
